[workspace]
members = [
    "circuit_sizes/2^2",
    "circuit_sizes/2^3",
    "circuit_sizes/2^4",
    "circuit_sizes/2^5",
    "circuit_sizes/2^6",
    "circuit_sizes/2^7",
    "circuit_sizes/2^8",
    "circuit_sizes/2^9",
    "circuit_sizes/2^10",
    "circuit_sizes/2^11",
    "circuit_sizes/2^12",
    "circuit_sizes/2^13",
    "circuit_sizes/2^14",
    "circuit_sizes/2^15",
    "circuit_sizes/2^16",
    "circuit_sizes/2^17",
    "circuit_sizes/2^18",
    "circuit_sizes/2^19",
    "circuit_sizes/2^20",
    "circuit_sizes/2^21",
    "circuit_sizes/2^22",
    "circuit_sizes/2^23",
    "circuit_sizes/2^24",
    "primitives/keccak256_32B",
    "primitives/keccak256_532B",
    "primitives/keccak256_32B_100_times",
    "primitives/keccak256_532B_10_times",
    "primitives/ecdsa_secp256k1",
    "primitives/compute_merkle_root_depth_4",
    "primitives/compute_merkle_root_depth_32",
    "primitives/verify_proof",
    "primitives/storage_proof_depth_8"
]
