hash_path = ["0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000", "0x0000000000000000000000000000000000000000000000000000000000000000"]
index = "0"
leaf = "0x0000000000000000000000000000000000000000000000000000000000000000"
